name: Build Go Project and Create Release
on:
    push:
        branches: [release]

permissions:
    contents: write

jobs:
    build_and_release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-20.04]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.20.x"

            - name: Linux
              if: matrix.os == 'ubuntu-20.04'
              run: |
                  go build -ldflags="-s -w" -o tgpt-linux-amd64
                  GOARCH=386 go build -ldflags="-s -w" -o tgpt-linux-i386
                  GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-linux-arm64
                  GOARCH=amd64 go build -ldflags="-s -w" -o tgpt-mac-amd64
                  GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-mac-arm64
                  GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o tgpt-amd64.exe
                  GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-arm64.exe
                  GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o tgpt-i386.exe
                  GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o tgpt-mac-amd64
                  GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-mac-arm64

            - name: Upload Artifacts
              id: upload-artifacts
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      tgpt-linux-amd64
                      tgpt-linux-i386
                      tgpt-linux-arm64
                      tgpt-amd64.exe
                      tgpt-i386.exe
                      tgpt-mac-amd64
                      tgpt-mac-arm64
                  token: ${{ secrets.GITHUB_TOKEN }}
                  draft: true
                  tag_name: v
                  name: tgpt